[package]
name = "faceTest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustface = "0.1.7"
bytes = "1.5.0"
image = "0.24.7"
imageproc = "0.23.0"